### ISSUE TITLE
broken link in description of project

### ISSUE THREAD

**Issue by sje30** [jmtd/detachment#1]
The link at the top of your description on the github home page for this project points to:
 http://jmtd.net/detachment/

that links no longer works.  Should it be something like:

https://jmtd.net/log/mail_archiving/2/

**Comment by jmtd** [comment]
Thanks!

**Comment by jmtd** [comment]
I keep meaning to return to this project and tidy it up, maybe one day!

**Comment by sje30** [comment]
it just cleared up my inbox nicely, thank you!
